=== triplea-game/triplea/data/games/strategy/engine/xml/game.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT game (info, loader, map, resourceList?, playerList, unitList, gamePlay, production?, attatchmentList? , initialize?, propertyList?)>

<!-- version must be in the form xx.xx or xx.xx.xx where xx is a positive integer -->
<!ELEMENT info EMPTY>
<!ATTLIST info
	name CDATA #REQUIRED
	version CDATA #REQUIRED
>

<!-- javaClass must implement the IGameLoader interface -->
<!ELEMENT loader EMPTY>
<!ATTLIST loader 
	javaClass CDATA #REQUIRED
>

<!ELEMENT map ((grid | territory)+ , connection*, remove-connection*)>
	<!ELEMENT grid EMPTY>
	<!ATTLIST grid
		name CDATA #REQUIRED
		type (square) #REQUIRED
		x CDATA #REQUIRED
		y CDATA #REQUIRED
		horizontal-connections (explicit | implicit) 'explicit'
		vertical-connections (explicit | implicit) 'explicit'
		diagonal-connections (explicit | implicit) 'explicit'
	>

	<!ELEMENT territory EMPTY>
	<!ATTLIST territory
		name CDATA #REQUIRED
		water (true | false)  "false"
	>
	<!-- connections are two way -->
	<!ELEMENT connection EMPTY>
	<!ATTLIST connection
		t1 CDATA #REQUIRED 
		t2 CDATA #REQUIRED
	>

	<!ELEMENT remove-connection EMPTY>
	<!ATTLIST remove-connection
		t1 CDATA #REQUIRED 
		t2 CDATA #REQUIRED
	>

<!ELEMENT resourceList (resource+) >
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource 
		name ID #REQUIRED
	>

<!ELEMENT unitList (unit+) >
	<!ELEMENT unit EMPTY>
	<!ATTLIST unit 
		name ID #REQUIRED
	>

<!ELEMENT playerList (player+, alliance*) >
	<!ELEMENT player EMPTY>
	<!ATTLIST player
		name ID #REQUIRED
		optional (true | false) 'false'
	>
	<!ELEMENT alliance EMPTY>

	<!ATTLIST alliance
		player IDREF #REQUIRED 
		alliance CDATA #REQUIRED
	>

	

		
<!ELEMENT gamePlay (delegate+, sequence)>
	<!ELEMENT delegate EMPTY>
	<!-- javaClass must implement Delegate
		 1 instance created per delegate declaraction, ie 1 instance per name -->
	<!ATTLIST delegate
		name ID #REQUIRED
		javaClass CDATA #REQUIRED
		display CDATA #IMPLIED
	>
	<!-- if no player given, then delegate is initialized with a null player -->
	<!-- max run count is the maximum number of times that a delegate can run, if specified must be > 0, if not specified its infinity-->
	<!ELEMENT sequence (step+)>
		<!ELEMENT step (stepProperty*)>
		<!ATTLIST step
			name ID #REQUIRED
			delegate IDREF #REQUIRED
			player IDREF #IMPLIED
			maxRunCount CDATA #IMPLIED
			display CDATA #IMPLIED
		>
			<!ELEMENT stepProperty EMPTY>
			<!ATTLIST stepProperty
				name CDATA #REQUIRED
				value CDATA #REQUIRED
			>
		

<!ELEMENT production (productionRule+, productionFrontier+, playerProduction+)>
	<!ELEMENT productionRule (cost+ , result+)>
	<!ATTLIST productionRule 
		name ID #REQUIRED
	>
		<!ELEMENT cost EMPTY>
		<!ATTLIST cost
			resource IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
		<!ELEMENT result EMPTY>
		<!ATTLIST result
			resourceOrUnit IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
	<!ELEMENT productionFrontier (frontierRules+)>
	<!ATTLIST productionFrontier
		name ID #REQUIRED
	>
		<!ELEMENT frontierRules EMPTY>
		<!ATTLIST frontierRules 
			name IDREF #REQUIRED
		>
	<!ELEMENT playerProduction EMPTY>
	<!ATTLIST playerProduction
	    player IDREF #REQUIRED
	    frontier IDREF #REQUIRED
	>
	
<!-- attatchments must implement Attatchment -->
<!ELEMENT attatchmentList (attatchment+) >
	<!ELEMENT attatchment (option+)>
	<!ATTLIST attatchment 
		name CDATA #REQUIRED
		attatchTo CDATA #REQUIRED
		javaClass CDATA #REQUIRED
		type (unitType | territory | resource | player)  "unitType"
	>
		<!ELEMENT option EMPTY> 
		<!ATTLIST option
			name CDATA #REQUIRED
			value CDATA #REQUIRED
		>

<!ELEMENT initialize (ownerInitialize?, unitInitialize?, resourceInitialize?) >
	<!ELEMENT ownerInitialize (territoryOwner+) >
		<!ELEMENT territoryOwner EMPTY>
		<!ATTLIST territoryOwner 
			territory CDATA #REQUIRED
			owner IDREF #REQUIRED
		>
	<!ELEMENT unitInitialize (unitPlacement*, heldUnits*) >
		<!-- units are owned by no one if owner isnt set -->
		<!ELEMENT unitPlacement EMPTY>
		<!ATTLIST unitPlacement
			unitType IDREF #REQUIRED
			territory CDATA #REQUIRED
			quantity CDATA #REQUIRED
			owner IDREF #IMPLIED
		>
		<!-- units that have not been placed yet -->
		<!ELEMENT heldUnits EMPTY>
		<!ATTLIST heldUnits 
			unitType IDREF #REQUIRED
			player IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
	<!ELEMENT resourceInitialize (resourceGiven+) >
		<!ELEMENT resourceGiven EMPTY>
		<!ATTLIST resourceGiven
			player IDREF #REQUIRED
			resource IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
		
<!ELEMENT propertyList (property*)>
	<!ELEMENT property (boolean?, string?, number?, list?) >
	<!-- can the player edit this on start up? if true then the type must be specified with a nested element -->
	<!ATTLIST property
		name CDATA #REQUIRED
		value CDATA #REQUIRED
		editable (true | false) "false"
	>
		<!ELEMENT boolean EMPTY>
		<!ATTLIST boolean
		>
		<!ELEMENT string EMPTY>
		<!ATTLIST string
		>
		<!ELEMENT number EMPTY>
		<!-- currently only integers are supported -->
		<!ATTLIST number
			max CDATA #REQUIRED
			min CDATA #REQUIRED
		>
		<!ELEMENT list EMPTY>
		<!-- a comma seperated list of possible values -->
		<!ATTLIST list
			values CDATA #REQUIRED
		>

=== triplea-game/triplea/data/games/strategy/engine/xml/GameExample.xml
<?xml version="1.0" ?>
<!DOCTYPE game SYSTEM "game.dtd">

<game>

	<info name="gameExample" version="1.0" />
	
	<loader javaClass="games.strategy.engine.xml.TestGameLoader"/>
		
	
	<map>
		<territory name="canada"/>
		<territory name="us"/>
		<territory name="atlantic" water="true"/>
		<connection t1="canada" t2="us"/>
	</map>
	<resourceList>
		<resource name="gold"/>
		<resource name="silver"/>
	</resourceList>
	<playerList>
		<player name="chretian" optional="true"/>
		<player name="bush" optional="false"/>
		<player name="castro" optional="false"/>
		<alliance player1="chretian" player2="castro"/>
	</playerList>
	<unitList>
		<unit name="inf"/>
	</unitList>
	<gamePlay>
		<delegate name="battle" javaClass="games.strategy.engine.xml.TestDelegate"/>
		<delegate name="move" javaClass="games.strategy.engine.xml.TestDelegate"/>
		<sequence>
			<step name="noPlayer" delegate="move" />
			<step name="usMove" delegate="move" player="bush"/>
			<step name="usFight" delegate="battle" player="bush"/>
			<step name="canMove" delegate="move" player="chretian"/>
			<step name="canFight" delegate="battle" player="chretian"/>
		</sequence>
	</gamePlay>
	<production>
		<productionRule name="infForGold">
			<cost resource="gold" quantity="3" />
			<result resourceOrUnit="inf" quantity="1"/>
		</productionRule>
		<productionRule name="infForSilver">
			<cost resource="silver" quantity="5" />
			<result resourceOrUnit="inf" quantity="1"/>
		</productionRule>
		<productionRule name="infForSilverAndGold">
			<cost resource="silver" quantity="1" />
			<cost resource="silver" quantity="1" />
			<result resourceOrUnit="inf" quantity="5"/>
		</productionRule>
		<productionFrontier name="usProd">
			<frontierRules name="infForGold"/>
			<frontierRules name="infForSilver"/>
		</productionFrontier>
		<productionFrontier name="canProd">
			<frontierRules name="infForSilverAndGold"/>
		</productionFrontier>
		<playerProduction player="bush" frontier="usProd" />
		<playerProduction player="chretian" frontier="canProd" />		
	</production> 

	<attatchmentList>
		<attatchment name="infAttatchment" attatchTo="inf" javaClass="games.strategy.engine.xml.TestAttatchment" type="unitType">
			<option name="value" value="inf"/>
		</attatchment>
		<attatchment name="resourceAttatchment" attatchTo="gold" javaClass="games.strategy.engine.xml.TestAttatchment" type="resource">
			<option name="value" value="gold"/>
		</attatchment>
		<attatchment name="territoryAttatchment" attatchTo="us" javaClass="games.strategy.engine.xml.TestAttatchment" type="territory">
			<option name="value" value="us of a"/>
		</attatchment>
		<attatchment name="playerAttatchment" attatchTo="chretian" javaClass="games.strategy.engine.xml.TestAttatchment" type="player">
			<option name="value" value="liberal"/>
		</attatchment>
	</attatchmentList>
	<initialize>
		<ownerInitialize>
			<territoryOwner territory="us" owner="bush"/>
			<territoryOwner territory="canada" owner="chretian"/>
		</ownerInitialize>
		<unitInitialize>
			<unitPlacement unitType="inf" territory="canada" quantity="5" owner="chretian"/>
			<unitPlacement unitType="inf" territory="us" quantity="150" owner="bush"/>
			<heldUnits unitType="inf" player="bush" quantity="20"/>
		</unitInitialize>
		<resourceInitialize>
			<resourceGiven player="chretian" resource="gold" quantity="100"/>
			<resourceGiven player="chretian" resource="silver" quantity="200"/>
		</resourceInitialize>
	</initialize>
		


	
</game>

=== triplea-game/triplea/maps/unclassified/games/n_puzzle_3x3.xml
<?xml version="1.0" ?>
<!DOCTYPE game SYSTEM "game.dtd">

<game>

	<info name="Eight puzzle" version="1.0"/>
	
	<loader javaClass="games.puzzle.slidingtiles.NPuzzle"/>
	
	<map>
		<grid name="gameboard" type="square" x="3" y="3" horizontal-connections="implicit" vertical-connections="implicit"/>
	</map>
	
	<playerList>
		<!-- In turn order -->
		<player name="Player" optional="false"/>
	</playerList>

	<gamePlay>
		<delegate name="init" javaClass="games.puzzle.slidingtiles.delegate.InitializationDelegate" display="Initialize Game"/>
		<delegate name="play" javaClass="games.puzzle.slidingtiles.delegate.PlayDelegate" display="Play"/>
		<delegate name="endTurn" javaClass="games.puzzle.slidingtiles.delegate.EndTurnDelegate" display="Check for winner"/>
		
		<sequence>
			<step name="gameInit" delegate="init" maxRunCount="1"/>
			
			<step name="gamePlay" delegate="play" player="Player"/>
			<step name="gameEndTurn" delegate="endTurn" />

		</sequence>
	</gamePlay>

	<propertyList>
		<property name="mapName" value="8_puzzle" editable="false" />
	    <property name="Difficulty Level" value="7" editable="true">
        	<number min="0" max="10000"/>
        </property>
        <property name="Background" value="" editable="true"><file/></property>
        
        <property name="notes">
        	<value><![CDATA[   
        	<h1>Eight Puzzle</h1>     	
        	A 3x3 n puzzle game.
        	]]></value>        	       
        </property>
        
	</propertyList>
		
</game>

=== triplea-game/triplea/games/tictactoe.xml
<?xml version="1.0" ?>
<!DOCTYPE game SYSTEM "game.dtd">

<game>

	<info name="Tic Tac Toe" version="0.1"/>
	
	<loader javaClass="games.puzzle.tictactoe.TicTacToe"/>
	
	<map>
		<grid type="square" name="main_board" x="3" y="3"/>
	</map>
	
	
	<playerList>
		<player name="X" optional="false"/>
		<player name="O" optional="false"/>
	</playerList>
	
	
	<unitList>
		<unit name="ticmark"/>
	</unitList>


	<gamePlay>
		<delegate name="play" javaClass="games.puzzle.tictactoe.delegate.PlayDelegate" display="Play"/>
		<delegate name="endTurn" javaClass="games.puzzle.tictactoe.delegate.EndTurnDelegate" display="Checking for a winner"/>
				
		<sequence>

			<step name="xPlay" delegate="play" player="X"/>
			<step name="xEndTurn" delegate="endTurn"/>

			<step name="oPlay" delegate="play" player="O"/>
			<step name="oEndTurn" delegate="endTurn"/>

		</sequence>
	</gamePlay>


	<propertyList>
		<property name="mapName" value="tictactoe" editable="false" />		
	</propertyList>
	
</game>
